name: wdune
version: '1.952'
summary: simple X3D/VRML NURBS/Superformula 3D modeller and animation tool
description: X3D/VRML editor, simple NURBS/Superformula 3D modeller and animation tool
type: app
base: core18
apps:
    wdune:
        command: dune -fn 9x15bold -x3dv 
        plugs:
            - desktop
            - network

parts:
    wdune:
        source: ftp://ftp.ourproject.org/pub/wdune/wdune-1.952.tar.bz2
        plugin: autotools

# access OpenSubdiv in /usr/local
passthrough:
    layout:
        /usr/local:
            bind: $SNAP/usr/local

build-packages:
    - make
    - bison
    - flex
    - gawk
    - m4
    - x11proto-core-dev
    - libexpat1-dev
    - libxmu-dev
    - xbase-clients
    - libxi-dev 
    - libgl-dev
    - libglu-dev
    - libmotif-dev
    - libpng-dev
    - libjpeg-dev
    - g++
    - gcc
    - libcurl4-openssl-dev
    - libfreetype6-dev
    - libcgal-dev
    - libavcodec-dev
    - libavutil-dev
    - libavformat-dev
    - libavresample-dev
    - libswscale-dev
    - libswresample-dev
    - ttf-bitstream-vera
    - xfonts-base 
    - gedit
    - xdg-utils
    - aqsis
    - povray
    - imagemagick
    - kolourpaint
    - audacity
    - rcs
